### ISSUE TITLE
Could you please provide the trained models?

### ISSUE THREAD

**Issue by hongyuanyu** [MCG-NJU/MixFormerV2#1]

**Comment by yutaocui** [comment]
We'll provide trained models and raw results in a few days.

**Comment by yutaocui** [comment]
Now you can access the models at [https://drive.google.com/drive/folders/1soQMZyvIcY7YrYrGdk6MCstTPlMXNd30](url).

**Comment by yutaocui** [comment]
Now you can access the models at [google dirve](https://drive.google.com/drive/folders/1soQMZyvIcY7YrYrGdk6MCstTPlMXNd30).
