### ISSUE TITLE
/data2/MixFormerV2-main/experiments/mixformer2_vit_online/288_depth8_score.yaml,这个配置文件

### ISSUE THREAD

**Issue by achangzx** [MCG-NJU/MixFormerV2#13]
这个配置文件中默认是使用公共数据集进行训练，如何修改成自定义的数据集呢，自定义的数据集标注格式使用CocoVID是否可行呢

**Comment by achangzx** [comment]
Solved, you can forge your own coco data set, modify the annotation in /data/coco to be your own json file, and you can directly train your own data set.

**Comment by songtianhui** [comment]
Cool!
