### ISSUE TITLE
size mismatch for box_head while training

### ISSUE THREAD

**Issue by wangwuwei** [MCG-NJU/MixFormerV2#15]
The paramter FEAT_SZ in teacher_288_depth12/student_288_depth12/student_288_depth8.yaml is 72, while it is set to 96 in 288_depth8_score.yaml. It leads to size mismatch for box_head when I try to train mixformer2_vit_online after training mixformer2_vit and mixformer2_vit_stu.

**Comment by songtianhui** [comment]
You can manually set the FEAT_SZ parameter to 72. Because 96 is for teacher of MixViT-large.

**Comment by wangwuwei** [comment]
> You can manually set the FEAT_SZ parameter to 72. Because 96 is for teacher of MixViT-large.

OK, I see. Thanks for your prompt response.

**Comment by litingsjj** [comment]
@songtianhui Can you provide MixViT-large teacher model? The model named MixFormer2-288-12-ep0500.pth.tar is  FEAT_SZ =72.
