### ISSUE TITLE
执行一阶段训练命令出现run training.py: error:unrecognized arguments:--local rank=1的错误

### ISSUE THREAD

**Issue by wangguijiepedeval** [MCG-NJU/MixFormerV2#25]
按照提供的中文版本训练教程进行复现的过程中执行第一阶段训练命令：
python tracking/train.py \
 --script mixformer2_vit \
 --config student_288_depth12 \
 --save_dir . \
 --distill 1 \
 --script_teacher mixformer_vit \
 --config_teacher teacher_mixvit_b \
 --checkpoint_teacher_path ./models/mixformer_vit_base_online.pth.tar \
 --mode multiple --nproc_per_node 8
 出现以下错误：
![2df75c95b2d273df720dd2c8a3b1e84](https://github.com/MCG-NJU/MixFormerV2/assets/92999048/bd99d83f-d7c8-4aef-970b-df86551013fd)

**Comment by wangguijiepedeval** [comment]
好像是代码写错了一点：
![image](https://github.com/MCG-NJU/MixFormerV2/assets/92999048/292e806c-ed6c-4334-ac4e-9602ef869b7e)
应该是下划线？

**Comment by songtianhui** [comment]
对，你改成下划线看下，不同的torch版本可能参数名略有区别
