### ISSUE TITLE
错误：AttributeError: 'EasyDict' object has no attribute 'REMOVE_LAYERS'？如何处理！

### ISSUE THREAD

**Issue by wangguijiepedeval** [MCG-NJU/MixFormerV2#26]
根据中文训练教程执行第一阶段训练出现以下错误：
![image](https://github.com/MCG-NJU/MixFormerV2/assets/92999048/55c69766-2120-4dc7-ac64-c07a7b83ddb1)
根据提示的信息去lib.config下找到一阶段训练用到的mixformer2_vit，然后发现里面没有定义cfg.TRAIN.REMOVE_LAYERS。
但在train/base_functions下用到了cfg.TRAIN.REMOVE_LAYERS：
![image](https://github.com/MCG-NJU/MixFormerV2/assets/92999048/114f1b30-aa2c-42c5-a6d9-f76e0f8ed6ff)

只有在mixformer2_vit_stu里才有定义：cfg.TRAIN.REMOVE_LAYERS = []

一阶段执行训练的命令：
CUDA_VISIBLE_DEVICES=4,5 python tracking/train.py \
 --script mixformer2_vit \
 --config student_288_depth12 \
 --save_dir . \
 --distill 1 \
 --script_teacher mixformer_vit \
 --config_teacher teacher_mixvit_b \
 --checkpoint_teacher_path ./models/mixformer_vit_base_online.pth.tar \
 --mode multiple --nproc_per_node 2

期望得到解答，不胜感激！

**Comment by songtianhui** [comment]
抱歉确实有这个小问题，感谢指出，在mixformer2_vit的config.py中也加上该行即可。这个阶段默认不会remove，置空即可。
